export enum Plan {
  FREE = 'FREE',
  STARTER = 'STARTER',
  PRO = 'PRO',
  ENTERPRISE = 'ENTERPRISE',
}

export enum TenantStatus {
  ACTIVE = 'ACTIVE',
  SUSPENDED = 'SUSPENDED',
  TRIAL = 'TRIAL',
}

export enum UserRole {
  SUPER_ADMIN = 'SUPER_ADMIN',
  ADMIN = 'ADMIN',
  OPERATOR = 'OPERATOR',
  SUPERVISOR = 'SUPERVISOR',
  REQUESTER = 'REQUESTER',
  PROVIDER_USER = 'PROVIDER_USER',
  AUDITOR = 'AUDITOR',
}

export enum UserStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  PENDING = 'PENDING',
}

export enum PropertyType {
  BUILDING = 'BUILDING',
  HOUSE = 'HOUSE',
  COMPLEX = 'COMPLEX',
  OFFICE = 'OFFICE',
  COMMERCIAL = 'COMMERCIAL',
}

export enum UnitType {
  APARTMENT = 'APARTMENT',
  LOCAL = 'LOCAL',
  COMMON_AREA = 'COMMON_AREA',
  PARKING = 'PARKING',
  STORAGE = 'STORAGE',
  OFFICE = 'OFFICE',
}

export enum ProviderStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  PENDING = 'PENDING',
  SUSPENDED = 'SUSPENDED',
}

export enum TicketStatus {
  NEW = 'NEW',
  RECEIVED = 'RECEIVED',
  IN_REVIEW = 'IN_REVIEW',
  ASSIGNED = 'ASSIGNED',
  AWAITING_QUOTE = 'AWAITING_QUOTE',
  QUOTE_RECEIVED = 'QUOTE_RECEIVED',
  PENDING_APPROVAL = 'PENDING_APPROVAL',
  APPROVED = 'APPROVED',
  SCHEDULING_VISIT = 'SCHEDULING_VISIT',
  IN_PROGRESS = 'IN_PROGRESS',
  PAUSED = 'PAUSED',
  COMPLETED = 'COMPLETED',
  VALIDATED = 'VALIDATED',
  CLOSED = 'CLOSED',
  CANCELLED = 'CANCELLED',
}

export enum Priority {
  CRITICAL = 'CRITICAL',
  HIGH = 'HIGH',
  MEDIUM = 'MEDIUM',
  LOW = 'LOW',
}

export enum TicketSource {
  WEB = 'WEB',
  APP = 'APP',
  WHATSAPP = 'WHATSAPP',
  EMAIL = 'EMAIL',
  MANUAL = 'MANUAL',
}

export enum EventType {
  STATUS_CHANGE = 'STATUS_CHANGE',
  MESSAGE = 'MESSAGE',
  FILE_UPLOAD = 'FILE_UPLOAD',
  QUOTE_SENT = 'QUOTE_SENT',
  QUOTE_APPROVED = 'QUOTE_APPROVED',
  QUOTE_REJECTED = 'QUOTE_REJECTED',
  VISIT_SCHEDULED = 'VISIT_SCHEDULED',
  VISIT_CONFIRMED = 'VISIT_CONFIRMED',
  VISIT_RESCHEDULED = 'VISIT_RESCHEDULED',
  VISIT_CANCELLED = 'VISIT_CANCELLED',
  CHECKIN = 'CHECKIN',
  CHECKOUT = 'CHECKOUT',
  EVIDENCE_UPLOADED = 'EVIDENCE_UPLOADED',
  ASSIGNMENT = 'ASSIGNMENT',
  PRIORITY_CHANGE = 'PRIORITY_CHANGE',
  SLA_ALERT = 'SLA_ALERT',
  NOTE = 'NOTE',
  SYSTEM = 'SYSTEM',
}

export enum Visibility {
  INTERNAL = 'INTERNAL',
  PROVIDER = 'PROVIDER',
  CLIENT = 'CLIENT',
  ALL = 'ALL',
}

export enum QuoteStatus {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  EXPIRED = 'EXPIRED',
}

export enum VisitStatus {
  SCHEDULED = 'SCHEDULED',
  CONFIRMED = 'CONFIRMED',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
  RESCHEDULED = 'RESCHEDULED',
}

export enum AttachmentCategory {
  BEFORE = 'BEFORE',
  AFTER = 'AFTER',
  QUOTE_DOC = 'QUOTE_DOC',
  DOCUMENT = 'DOCUMENT',
  EVIDENCE = 'EVIDENCE',
  OTHER = 'OTHER',
}

export enum NotificationChannel {
  PUSH = 'PUSH',
  EMAIL = 'EMAIL',
  WHATSAPP = 'WHATSAPP',
  IN_APP = 'IN_APP',
}

export enum NotificationStatus {
  PENDING = 'PENDING',
  SENT = 'SENT',
  FAILED = 'FAILED',
  READ = 'READ',
}
